# Generated by Django 5.0.6 on 2024-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Banda', 'Banda'), ('Solo', 'Solo')], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=20)),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG')], max_length=3)),
            ],
        ),
    ]
